# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller 配置文件"""

block_cipher = None

a = Analysis(
    ['run.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'claude_agent_sdk',
        'anthropic',
        'anyio',
        'prompt_toolkit',
        'pygments',
        'dotenv',
        'yaml',
        'my_agent',
        'my_agent.cli',
        'my_agent.commands',
        'my_agent.ui',
        'my_agent.permissions',
        'my_agent.highlight',
        'my_agent.input',
        'my_agent.image',
        'my_agent.mcp',
        'my_agent.mcp.server',
        'my_agent.plan_mode',
        'my_agent.plan_ui',
        'my_agent.skills',
        'my_agent.setup_wizard',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='my_claude',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)